name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{secrets.OS}}
    steps:
      - uses: ${{secrets.ACTION_ONE}}
      - uses: ${{secrets.ACTION_TWO}} # This is the action
        with:
          heroku_api_key: ${{secrets.KEY}}
          heroku_app_name: ${{secrets.APP}} #Must be unique in Heroku
          heroku_email: ${{secrets.EMAIL}}