name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.7.8 # This is the action
        with:
          heroku_api_key: ${{secrets.KEY}}
          heroku_app_name: "api-account-staging" #Must be unique in Heroku
          heroku_email: "abbasiathar@hotmail.com"